# Introduction à django {-#django}

django permet de construire des sites web modulaires, composés de plusieurs
applications indépendantes. Toute commande liée à un projet django passe par
le script `manage.py`. Celui-ci permet de lancer le serveur, se connecter à la 
base de données de l'application, lancer une session Python interactive qui permet
de tester le code développé.

## Guide de commandes de base {-#commands}

* Créer un nouveau site : `django-admin startproject <project-name>`

À l'intérieur du dossier du projet, les commandes suivantes sont disponibles :

* Créer une nouvelle application : `./manage.py startapp <app-name>`
* Se connecter à la base de données : `./manage.py dbshell`
* Pour lancer une session python interactive : `./manage.py shell`

## Commandes développées par l'équipe {-#commandsbis}

* Exécuter un script sql à l'intérieur de la base de données du site : 
`./manage.py dbexec script.sql`
* Importer des données (en format FASTA) :
  * Des génomes `./manage.py importgenome fichier_genome.fa`
  * Des gènes `./manage.py importgenes fichier_genes.fa`
  * Des protéines `./manage.py importproteins fichier_proteines.fa`

Le fichier `runall.bash` permet de tout exécuter: créer les tables de la base, 
importer tous les génomes, tous les gènes et toutes les protéines (attention, 
un dossier appelé `Data` doit contenir tous les fichier et doit se trouver
à la racine du projet).



